Compatibility with 5.14: 'dm_report_zones_cb' undeclared
In 912e887505a0 ("dm: Introduce dm_report_zones()") `dm_report_zones_cb'
is unexpired and it's suggested to use `dm_report_zones' helper. Error
message:

/usr/src/RPM/BUILD/dm-secdel-1.0.7/dm-secdel.c: In function 'secdel_report_zones':
/usr/src/RPM/BUILD/dm-secdel-1.0.7/dm-secdel.c:344:36: error: 'dm_report_zones_cb' undeclared (first use in this function); did you mean 'dm_report_zones_fn'?
  344 |                                    dm_report_zones_cb, args);
      |                                    ^~~~~~~~~~~~~~~~~~
      |                                    dm_report_zones_fn