Fix build on v6.0 (bio_op)
'bio_op' define is introduced in v4.10-rc1~112^2~42 and made inline
v6.0-rc1~178^2~83, do not trigger old kernels fallback on new kernels.

  /usr/src/RPM/BUILD/dm-secdel-1.0.9/dm-secdel.c: In function 'op_discard':
  /usr/src/RPM/BUILD/dm-secdel-1.0.9/dm-secdel.c:196:12: error: 'struct bio' has no member named 'bi_rw'
    196 |         bio->bi_rw & REQ_DISCARD
	|            ^~
  /usr/src/RPM/BUILD/dm-secdel-1.0.9/dm-secdel.c:196:22: error: 'REQ_DISCARD' undeclared (first use in this function); did you mean 'ITER_DISCARD'?
    196 |         bio->bi_rw & REQ_DISCARD
	|                      ^~~~~~~~~~~
	|                      ITER_DISCARD

Signed-off-by: Vitaly Chikunov <vt@altlinux.org>