Fix compiling when CONFIG_BLK_DEV_ZONED is enabled
Will compile since v5.3.

Error:

/usr/src/RPM/BUILD/dm-secdel-1.0.7/dm-secdel.c: In function 'secdel_report_zones':
/usr/src/RPM/BUILD/dm-secdel-1.0.7/dm-secdel.c:338:43: error: implicit declaration of function 'linear_map_sector' [-Werror=implicit-function-declaration]
  338 |  ret = blkdev_report_zones(lc->dev->bdev, linear_map_sector(ti, sector),
/usr/src/RPM/BUILD/dm-secdel-1.0.7/dm-secdel.c:338:8: error: too many arguments to function 'blkdev_report_zones'
  338 |  ret = blkdev_report_zones(lc->dev->bdev, linear_map_sector(ti, sector),