Compatibility with kernels below 5.15 (DMEMIT)
`DMEMIT` is already requires `sz`.

  /usr/src/RPM/BUILD/dm-secdel-1.0.8/dm-secdel.c: In function 'secdel_status':
  ./include/linux/device-mapper.h:578:22: error: 'sz' undeclared (first use in this function); did you mean 's8'?
    578 | #define DMEMIT(x...) sz += ((sz >= maxlen) ? \
	|                      ^~
  /usr/src/RPM/BUILD/dm-secdel-1.0.8/dm-secdel.c:393:3: note: in expansion of macro 'DMEMIT'
    393 |   DMEMIT("%s %llu %s", lc->dev->name,
	|   ^~~~~~

Signed-off-by: Vitaly Chikunov <vt@altlinux.org>